### ISSUE TITLE
Package generates improper urls in sitemap.xml

### ISSUE THREAD

**Issue by Aniganesh** [aminnairi/rollup-plugin-sitemap#1]
**Describe the bug**

**To Reproduce**
Follow all the normal steps to set this up with rollup or vite which is built on rollup.

**Expected behaviour**
The generated sitemap.xml has all the urls in the right format.

**Actual behaviour**
The generated sitemap has urls that throw an error. The double slash is replaced by a single slash. ie., https://domain.com becomes https:/domain.com (note the single forward slash instead of two).

**Screenshots**
This image is a screenshot from the readme file. 
Please note the missing slash after the protocol, i.e., `https:/` instead of `https://`.
![image](https://github.com/aminnairi/rollup-plugin-sitemap/assets/47713754/45ff83d3-3c9e-47a2-bb52-dcb3a62730bb)

**Environment (please complete the following information):**
Not environment dependent.

Anyway:
 - OS: Ubuntu 22.04
 - Node  18.x.x, 20.x.x
 - Package 0.1.0

**Comment by aminnairi** [comment]
Hi!

Great catch on that error, I didn't see that coming.

It looks like it has something to do with the `require("path").join` function since this is what is used in the source-code to join the `baseUrl` with the `location`. 

I though that this function would be joining the urls altogether, but I guess there is an error in the built-in function.

```javascript
console.log(require("path").join("https://github.com", "home")); // https:/github.com/home
```

**Comment by jaybeeuu** [comment]
Using `path.join` causes a problem in windows too as it uses the _platform_ directory seperator (`/` or `\`). 

![image](https://github.com/aminnairi/rollup-plugin-sitemap/assets/2077433/e9fc6e34-d477-4d3e-b0a9-71546373a14c)

You'd be better to use [`path.posix.join`](https://nodejs.org/api/path.html#pathposix) which consistently uses `/`. ofc that doesn't solve your problem with the protocol. I think you should consider parsing the url with [`URL`](https://developer.mozilla.org/en-US/docs/Web/API/URL) then joining the `pathname`.

Would you accept a PR?

**Comment by aminnairi** [comment]
I didn't even know there was a `path.posix` property in the `path` package!

That is wonderful news, and I would gladly accept a pull request.

I just opened #3 if you need to discuss this further and/or propose a pull request that closes this issue.
